Enable excluding record fields
fluent/fluent-plugin-kafka pull request #415
Opened 2021-08-20 21:03 UTC by lucasMesquitaBorges

I would like to exclude fields from message record.

This is desirable when using another configs such as `headers_from_record`, wich duplicates data to message headers. With this config will be possible to move data to headers and remove from the message payload.

2021-08-23 02:03 UTC, kenhys requested changes
Could you also add a test for this change, please?

2021-08-23 02:03 UTC, kenhys commented on lib/fluent/plugin/out_kafka2.rb
> +              @exclude_field_acessors.each do |exclude_field_acessor|
It may be better to use 

```ruby
unless @exclude_fields.empty?
 ...
end
```

2021-08-23 02:03 UTC, kenhys commented on lib/fluent/plugin/out_rdkafka2.rb
> +      @exclude_fields.each do |field|
typo.

2021-09-06 18:36 UTC, lucasMesquitaBorges commented on lib/fluent/plugin/out_rdkafka2.rb
> +      @exclude_fields.each do |field|
Typo removed

2021-09-06 18:36 UTC, lucasMesquitaBorges commented on lib/fluent/plugin/out_kafka2.rb
> +              @exclude_field_acessors.each do |exclude_field_acessor|
Thanks! Applied!

2021-09-06 18:36 UTC, lucasMesquitaBorges commented on lib/fluent/plugin/out_kafka2.rb
> +      end
Applied

2021-09-06 18:36 UTC, lucasMesquitaBorges commented on lib/fluent/plugin/out_kafka2.rb
> +      @exclude_fields.each do |field|
Applied

2021-09-06 18:55 UTC, lucasMesquitaBorges commented
Hi @kenhys thanks for the code review!

I applied all changes you've requested, I also tried to test this new config but got some errors when trying to write a message to CI kafka broker wich I wasn't able to fix.

Following this pattern https://docs.fluentd.org/plugin-development/plugin-test-code#testing-output-plugins throws error on write method from `out_kafka2` at `producer.deliver_messages`.

Do you have any idea of how I can write a message to a topic when testing? From this point I'll be able to test!

2021-09-09 08:11 UTC, ashie reviewed
> Do you have any idea of how I can write a message to a topic when testing? From this point I'll be able to finish the tests!

I've fixed the failed test.
(While I working on it, I found another bug in the original code: e74af6e3ed89aad0a72a27002888ecaf5b5dd1d4)

2021-09-09 08:17 UTC, ashie approved these changes

2021-09-10 01:28 UTC, cosmo0920 approved these changes
I added a nit comment for record accessor notation description.
LGTM

2021-09-10 01:28 UTC, cosmo0920 commented on README.md
> +Fields must be specified using an array of dot notation `$.`, for example:
`$[...][...]` notation also can be handled in `record_accessor`.
But this notation is confusable. I'm OK to leave as-is.

2021-09-10 01:28 UTC, cosmo0920 commented on lib/fluent/plugin/out_kafka2.rb
> +        producer = @kafka.topic_producer(topic, **@producer_opts)
Ouch. 🤧

2021-09-10 01:28 UTC, cosmo0920 commented on test/plugin/test_out_kafka2.rb
> +      assert_equal([expected_message], actual_messages)
Oh, this is really good idea! :+1:

2021-09-10 01:28 UTC, cosmo0920 commented on test/plugin/test_out_kafka2.rb
> +      assert_equal([{'a' => 'b', 'message' => 'test'}], actual_messages)
:+1:

2021-09-10 04:17 UTC, merged